use super::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReleaseCandidateReviewStatus { NotReviewed, ReviewProjected, ReviewableWithCaveats, ReviewBlocked, ReviewIncomplete, InvalidReviewInput }
impl ReleaseCandidateReviewStatus { pub fn code(self)->&'static str { match self { Self::NotReviewed=>"not_reviewed", Self::ReviewProjected=>"review_projected", Self::ReviewableWithCaveats=>"reviewable_with_caveats", Self::ReviewBlocked=>"review_blocked", Self::ReviewIncomplete=>"review_incomplete", Self::InvalidReviewInput=>"invalid_review_input" }}}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum ReleaseCandidateReviewSection { ManifestSummary, Caveats, Blockers, UpstreamLinkage, ValidationSummary, ReviewFindings, AuthorityBoundaries }
impl ReleaseCandidateReviewSection { pub fn code(self)->&'static str { match self { Self::ManifestSummary=>"manifest_summary", Self::Caveats=>"caveats", Self::Blockers=>"blockers", Self::UpstreamLinkage=>"upstream_linkage", Self::ValidationSummary=>"validation_summary", Self::ReviewFindings=>"review_findings", Self::AuthorityBoundaries=>"authority_boundaries" }}}
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum ReleaseCandidateReviewFindingCategory { ManifestSupportability, ManifestBlocker, ManifestCaveat, UpstreamLinkage, ValidationSummary, TargetedCleanup, NoAuthorityBoundary }
impl ReleaseCandidateReviewFindingCategory { fn code(self)->&'static str { match self {Self::ManifestSupportability=>"manifest_supportability",Self::ManifestBlocker=>"manifest_blocker",Self::ManifestCaveat=>"manifest_caveat",Self::UpstreamLinkage=>"upstream_linkage",Self::ValidationSummary=>"validation_summary",Self::TargetedCleanup=>"targeted_cleanup",Self::NoAuthorityBoundary=>"no_authority_boundary"}}}
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum ReleaseCandidateReviewFindingSeverity { Info, Low, Medium, High, Blocking }
impl ReleaseCandidateReviewFindingSeverity { fn code(self)->&'static str { match self {Self::Info=>"info",Self::Low=>"low",Self::Medium=>"medium",Self::High=>"high",Self::Blocking=>"blocking"}}}
#[derive(Debug, Clone, PartialEq, Eq)] pub struct ReleaseCandidateReviewFinding { pub category:String, pub severity:String, pub detail:String, pub source:String }
#[derive(Debug, Clone, PartialEq, Eq)] pub struct ReleaseCandidateReviewManifestSummary { pub label_status:String, pub manifest_status:String, pub manifest_id:Option<String>, pub item_count:usize }
#[derive(Debug, Clone, PartialEq, Eq)] pub struct ReleaseCandidateReviewCaveatSummary { pub category:String, pub detail:String }
#[derive(Debug, Clone, PartialEq, Eq)] pub struct ReleaseCandidateReviewBlockerSummary { pub category:String, pub reason:String }
#[derive(Debug, Clone, PartialEq, Eq)] pub struct ReleaseCandidateReviewUpstreamLinkageSummary { pub category:String, pub source_surface:String, pub source_status:String, pub source_id:String }
#[derive(Debug, Clone, PartialEq, Eq)] pub struct ReleaseCandidateReviewValidationSummary { pub item_count:usize, pub present_count:usize, pub missing_count:usize, pub blocked_count:usize, pub rejected_count:usize }
#[derive(Debug, Clone, PartialEq, Eq)] pub struct ReleaseCandidateReviewCapabilitySurface { pub approval_enabled:bool, pub signing_enabled:bool, pub publishing_enabled:bool, pub deployment_enabled:bool, pub public_distribution_enabled:bool }
#[derive(Debug, Clone, PartialEq, Eq)] pub struct ReleaseCandidateReviewProjection { pub status:String, pub review_id:Option<String>, pub sections:Vec<String>, pub manifest_summary:ReleaseCandidateReviewManifestSummary, pub caveats:Vec<ReleaseCandidateReviewCaveatSummary>, pub blockers:Vec<ReleaseCandidateReviewBlockerSummary>, pub upstream_linkage:Vec<ReleaseCandidateReviewUpstreamLinkageSummary>, pub validation_summary:ReleaseCandidateReviewValidationSummary, pub review_findings:Vec<ReleaseCandidateReviewFinding>, pub boundary_statuses:Vec<String>, pub capability_surface:ReleaseCandidateReviewCapabilitySurface }

pub fn initial_release_candidate_review_projection()->ReleaseCandidateReviewProjection { ReleaseCandidateReviewProjection { status: ReleaseCandidateReviewStatus::NotReviewed.code().into(), review_id: None, sections: release_candidate_review_sections(), manifest_summary: ReleaseCandidateReviewManifestSummary{label_status:"not_labeled".into(),manifest_status:"not_generated".into(),manifest_id:None,item_count:0}, caveats:vec![], blockers:vec![], upstream_linkage:vec![], validation_summary:ReleaseCandidateReviewValidationSummary{item_count:0,present_count:0,missing_count:0,blocked_count:0,rejected_count:0}, review_findings:vec![], boundary_statuses: release_candidate_review_boundary_statuses(), capability_surface: release_candidate_review_capability_surface() }}
pub fn release_candidate_review_sections()->Vec<String>{let mut v=[ReleaseCandidateReviewSection::ManifestSummary,ReleaseCandidateReviewSection::Caveats,ReleaseCandidateReviewSection::Blockers,ReleaseCandidateReviewSection::UpstreamLinkage,ReleaseCandidateReviewSection::ValidationSummary,ReleaseCandidateReviewSection::ReviewFindings,ReleaseCandidateReviewSection::AuthorityBoundaries].into_iter().map(|x|x.code().to_string()).collect::<Vec<_>>();v.sort();v}
pub fn release_candidate_review_boundary_statuses()->Vec<String>{vec!["review_surface_only","non_authoritative_review","local_only_non_public","release_candidate_status_not_approved","release_readiness_not_approved","production_status_not_approved","public_use_not_approved","release_artifact_not_created","public_artifact_not_created","no_signing","no_publishing","no_deployment_artifact","no_public_distribution","no_public_download","no_github_release","no_release_tag","no_installer_activation","no_update_channel_activation"].into_iter().map(|s|s.to_string()).collect()}
fn release_candidate_review_capability_surface()->ReleaseCandidateReviewCapabilitySurface{ReleaseCandidateReviewCapabilitySurface{approval_enabled:false,signing_enabled:false,publishing_enabled:false,deployment_enabled:false,public_distribution_enabled:false}}

pub fn derive_release_candidate_review(manifest:&ReleaseCandidateEvidenceManifestProjection)->ReleaseCandidateReviewProjection{
 let mut p=initial_release_candidate_review_projection();
 p.manifest_summary=ReleaseCandidateReviewManifestSummary{label_status:manifest.label_status.clone(),manifest_status:manifest.manifest_status.clone(),manifest_id:manifest.manifest_id.clone(),item_count:manifest.items.len()};
 p.caveats=manifest.caveats.iter().map(|c|ReleaseCandidateReviewCaveatSummary{category:c.category.clone(),detail:c.detail.clone()}).collect(); p.caveats.sort_by(|a,b|a.category.cmp(&b.category));
 p.blockers=manifest.blockers.iter().map(|b|ReleaseCandidateReviewBlockerSummary{category:b.category.clone(),reason:b.reason.clone()}).collect(); p.blockers.sort_by(|a,b|a.category.cmp(&b.category));
 p.upstream_linkage=manifest.items.iter().map(|i|ReleaseCandidateReviewUpstreamLinkageSummary{category:i.category.clone(),source_surface:i.linkage.source_surface.clone(),source_status:i.linkage.source_status.clone(),source_id:i.linkage.source_id.clone()}).collect(); p.upstream_linkage.sort_by(|a,b|a.category.cmp(&b.category));
 p.validation_summary=ReleaseCandidateReviewValidationSummary{item_count:manifest.validation_summary.item_count,present_count:manifest.validation_summary.present_count,missing_count:manifest.validation_summary.missing_count,blocked_count:manifest.validation_summary.blocked_count,rejected_count:manifest.validation_summary.rejected_count};
 p.review_findings.push(ReleaseCandidateReviewFinding{category:ReleaseCandidateReviewFindingCategory::NoAuthorityBoundary.code().into(),severity:ReleaseCandidateReviewFindingSeverity::Info.code().into(),detail:"Review surface only with no approval/readiness authority.".into(),source:"boundary_statuses".into()});
 for b in &p.blockers { p.review_findings.push(ReleaseCandidateReviewFinding{category:ReleaseCandidateReviewFindingCategory::ManifestBlocker.code().into(),severity:ReleaseCandidateReviewFindingSeverity::Blocking.code().into(),detail:b.reason.clone(),source:b.category.clone()}); }
 for c in &p.caveats { let cat = if c.category=="targeted_cleanup_required" {ReleaseCandidateReviewFindingCategory::TargetedCleanup} else {ReleaseCandidateReviewFindingCategory::ManifestCaveat}; p.review_findings.push(ReleaseCandidateReviewFinding{category:cat.code().into(),severity:ReleaseCandidateReviewFindingSeverity::Medium.code().into(),detail:c.detail.clone(),source:c.category.clone()}); }
 p.review_findings.sort_by(|a,b| (&a.category,&a.severity,&a.detail).cmp(&(&b.category,&b.severity,&b.detail)));
 p.status = if manifest.manifest_status=="manifest_complete_with_caveats" { ReleaseCandidateReviewStatus::ReviewableWithCaveats.code().into() } else if !p.blockers.is_empty() { ReleaseCandidateReviewStatus::ReviewBlocked.code().into() } else if manifest.manifest_status=="not_generated" { ReleaseCandidateReviewStatus::ReviewIncomplete.code().into() } else { ReleaseCandidateReviewStatus::ReviewProjected.code().into() };
 let digest = format!("{}|{}|{}|{}",p.manifest_summary.manifest_status,p.caveats.len(),p.blockers.len(),p.review_findings.len()); p.review_id=Some(format!("rc-review-{:x}",simple_hash(&digest)));
 p
}
fn simple_hash(s:&str)->u64{ let mut h=1469598103934665603u64; for b in s.as_bytes(){ h^=*b as u64; h=h.wrapping_mul(1099511628211);} h }

#[cfg(test)] mod tests { use super::*; #[test] fn deterministic(){let m=initial_release_candidate_evidence_manifest_projection(); assert_eq!(derive_release_candidate_review(&m),derive_release_candidate_review(&m));}}
